name: Package Tests

on: [ push ]

jobs:
  format-code:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install 'black'
        run: |
          python -m pip install --upgrade pip
          python -m pip install black

      - name: Run 'black'
        run: black --check src/

      - name: Print formatting errors
        run: |
          out=$(black --diff src/)

          echo "${out}""
          echo "\`\`\`python" >> $GITHUB_STEP_SUMMARY
          echo "${out}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        if: ${{ failure() }}

  run-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup conda environment for tests
        run: |
          conda env create
          conda run -n ils-smoothing --live-stream pip install ".[dev]"

      - name: Run mypy
        run: conda run -n ils-smoothing --live-stream python ./scripts/run-mypy src
        if: ${{ !cancelled() }}

      - name: Run tests
        run: conda run -n ils-smoothing --live-stream pytest -v -rxXs .
        if: ${{ !cancelled() }}
