name: Package Tests

on: [ push ]

jobs:
  run-tests:
    name: Run unit tests.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install packages.
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Run pytest.
        run: pytest -v -rxXs .
